### ISSUE TITLE
Executing on windows requires manually fixing CRLF

### ISSUE THREAD

**Issue by nivpgir** [tokay-lang/tokay#34]
Tokay programs fail to parse when trying to execute them on windows due to "expecting EOF".

I am able to work around this by manually converting "\r\n" to "\n" (using emacs but I assume dos2unix would work as well).

I have a hunch that fixing it would be rather simple (adding a case for "\r\n" somewhere around [here](https://github.com/tokay-lang/tokay/blob/fc93560439bd426059badd0670d21f141d52274d/src/compiler/parser.rs#L35) and even tried to implement it myself, but failed to compile tokay, because of the same issue, after converting all *.tok files from the repo, I'm getting `thread 'main' has overflowed its stack` on every run of my locally built tokay (the one installed with `cargo install tokay` works fine) after which I stopped trying 😁.

any chance you can help/fix/support this?

Also, something else that I was wondering about (for a small parser I thought of implementing with tokay), is a string `len` function, it doesn't look like there's a builtin for it, and I'm not quite sure how to implement it with tokay itself. this is of course a different issue, but I didn't want to start spamming new issues 😅 

Cool language! I hope it grows.

**Comment by phorward** [comment]
Hello @nivpgir,

thank you very much for filing this issue, and apologize my late answer, there is something wrong with my notification settings so I didn't get an email and just "stumbled" over your issue a few minutes ago.

> any chance you can help/fix/support this?

Sure, this is a serious issue and should be supported. I'll fix it in a moment. You're right with your findings, it must be fixed at this location in the parser.

> Also, something else that I was wondering about (for a small parser I thought of implementing with tokay), is a string `len` function, it doesn't look like there's a builtin for it, and I'm not quite sure how to implement it with tokay itself. this is of course a different issue, but I didn't want to start spamming new issues sweat_smile

Sure, and this was also possible with Tokay v0.4, but is currently broken in Token v0.5 as the entire built-in and object concept is being redesigned and modularized:
```
 $ tokay
Tokay 0.4.0
>>> "hello".len
5
>>> 
```
I'll keep this in mind and will add a str_len()-builtin (which will than be callable like with tokay v0.4)

> Cool language! I hope it grows.

Thanks, and please report any bugs you're going to find. Tokay is still in a very early stage and features are currently in heavy development.

**Comment by nivpgir** [comment]
I appreciate your fix, regardless of the time, but compilation still fails on my setup, I still needed to run `dos2unix` on build.tok and even then I gotthese errors for all the builtins:
```
Line 2, column 1: Parse error, expecting end-of-file
error: Line 2, column 1: Parse error, expecting end-of-file
  --> src\builtin.rs:90:17
   |
90 | tokay_function!("chr(i)", {
   |                 ^^^^^^^^
```

I tried applying the fix for v0.4 and added:
```
[patch.crates-io]
tokay = { path = "../tokay-v0.4" }
```
to Cargo.toml and then the compilation succeeds, so it's probably happening because the fix isn't applied the to tokay 0.4 which is used to compile the current code.

not sure how you'd wanna deal with it, but at least now I know how to consistently compile tokay, so I can start debugging other bugs 😅

**Comment by phorward** [comment]
Hello @nivpgir!
 
> I tried applying the fix for v0.4 and added:
> 
> ```
> [patch.crates-io]
> tokay = { path = "../tokay-v0.4" }
> ```
> 
> to Cargo.toml and then the compilation succeeds, so it's probably happening because the fix isn't applied the to tokay 0.4 which is used to compile the current code.
> 
> not sure how you'd wanna deal with it, but at least now I know how to consistently compile tokay, so I can start debugging other bugs sweat_smile

Yeah right, Tokay v0.4 is currently a build dependency of Tokay v0.5 (current main branch at this time) and I won't gonna fix v0.4 because after release the build dependencies will be updated to Tokay v0.5 and the problem will be gone. 

Anyway, thanks for fixing it on your own. I would be very happy about more bug report and enhancement requests soon, and hope to present a more stable Tokay with the next release.
